import 'package:flutter/foundation.dart' show SynchronousFuture;
import 'package:flutter/material.dart';

import 'app_strings.dart';

/// Runtime string lookup for `ar` (default) and `en`.
///
/// Deliberately hand-written rather than generated by `gen_l10n`:
///   * the same language code is reused verbatim as the `Accept-Language`
///     header, so there is one canonical notion of "current language";
///   * no build step is introduced, matching the models decision in pubspec;
///   * a missing key is loud in debug (`assert`) but degrades to the key name
///     in release instead of throwing in front of a user.
class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  /// Arabic is the primary language of the store, so it is first and is the
  /// fallback for an unsupported device locale.
  static const List<Locale> supportedLocales = [
    Locale('ar'),
    Locale('en'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final instance = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(
      instance != null,
      'AppLocalizations.of() called without AppLocalizations.delegate in '
      'MaterialApp.localizationsDelegates.',
    );
    return instance ?? const AppLocalizations(Locale('ar'));
  }

  /// Language code as the API expects it (`ar` / `en`).
  String get languageCode => locale.languageCode == 'en' ? 'en' : 'ar';

  bool get isArabic => languageCode == 'ar';

  TextDirection get textDirection =>
      isArabic ? TextDirection.rtl : TextDirection.ltr;

  /// Looks up [key], falling back to Arabic and then to the key itself.
  String t(String key) {
    final entry = AppStrings.values[key];
    assert(entry != null, 'Missing translation key: $key');
    if (entry == null) return key;
    return entry[languageCode] ?? entry['ar'] ?? key;
  }

  /// Looks up [key] and substitutes `{name}` placeholders.
  ///
  /// Interpolation is done here rather than with string concatenation at call
  /// sites because Arabic word order differs from English — `'{n} منتج'` vs
  /// `'{n} products'` cannot be built by appending a suffix.
  String tf(String key, Map<String, Object?> args) {
    var result = t(key);
    args.forEach((name, value) {
      result = result.replaceAll('{$name}', value?.toString() ?? '');
    });
    return result;
  }

  /// Arabic pluralisation is simplified to the two forms the UI actually needs.
  ///
  /// Full CLDR Arabic has six categories (zero/one/two/few/many/other). The
  /// only places the app pluralises are item and result counts, where the
  /// idiomatic Egyptian retail phrasing is a bare numeral plus the singular
  /// ("٣ منتج"), so implementing all six would add branches no screen uses.
  String plural(int count, {required String one, required String other}) =>
      tf(count == 1 ? one : other, {'n': count});
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales
          .any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      // SynchronousFuture, NOT `async`. Strings come from a compile-time map
      // with no I/O, so there is nothing to await — and an `async` body yields
      // to the event loop, which makes Localizations withhold the subtree for
      // one frame. In the app that is an invisible flash of nothing; in a
      // widget test the first `pumpWidget` renders an empty tree and every
      // `find` fails.
      SynchronousFuture<AppLocalizations>(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

/// `context.l10n.t('key')` — shorter than the full `AppLocalizations.of(...)`
/// at every call site, which matters because almost every widget needs it.
extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
