// <auto-generated />
using System;
using FTD.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FTD.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713074256_AddProductFeaturesJson")]
    partial class AddProductFeaturesJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FTD.Domain.Entities.AttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<string>("ValueAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ValueEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.ToTable("AttributeValues");
                });

            modelBuilder.Entity("FTD.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescAr = "هواتف وتابلتات متينة بمواصفات عالية",
                            DescEn = "Rugged phones and tablets with high specs",
                            IsActive = true,
                            LogoPath = "/images/brands/doogee.png",
                            NameAr = "DOOGEE",
                            NameEn = "DOOGEE",
                            Slug = "doogee",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescAr = "مراوح محمولة وأجهزة ذكية للحياة اليومية",
                            DescEn = "Portable fans and smart devices for daily life",
                            IsActive = true,
                            LogoPath = "/images/brands/jisulife.png",
                            NameAr = "JisuLife",
                            NameEn = "JisuLife",
                            Slug = "jisulife",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescAr = "أجهزة تنظيف ذكية ومتطورة",
                            DescEn = "Smart and advanced cleaning devices",
                            IsActive = true,
                            LogoPath = "/images/brands/dreame.png",
                            NameAr = "Dreame",
                            NameEn = "Dreame",
                            Slug = "dreame",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("FTD.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("ShowOnHomepage")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Emoji = "📱",
                            IsActive = true,
                            NameAr = "تابلتات",
                            NameEn = "Tablets",
                            ShowOnHomepage = true,
                            Slug = "tablets",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Emoji = "🌀",
                            IsActive = true,
                            NameAr = "مراوح محمولة",
                            NameEn = "Fans",
                            ShowOnHomepage = true,
                            Slug = "fans",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Emoji = "📷",
                            IsActive = true,
                            NameAr = "كاميرات ويب",
                            NameEn = "Webcams",
                            ShowOnHomepage = true,
                            Slug = "webcams",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("FTD.Domain.Entities.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapEmbedUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowAddress")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowFacebook")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInstagram")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowMap")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPhone")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPhone2")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowTikTok")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowWhatsApp")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowWorkingHours")
                        .HasColumnType("bit");

                    b.Property<string>("TikTok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHoursAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHoursEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressAr = "القاهرة، مصر الجديدة",
                            AddressEn = "Cairo, Heliopolis",
                            City = "Cairo",
                            Email = "info@unishop.com",
                            Facebook = "https://facebook.com/unishop",
                            Instagram = "https://instagram.com/unishop",
                            Phone = "+20 100 000 0000",
                            ShowAddress = true,
                            ShowEmail = true,
                            ShowFacebook = true,
                            ShowInstagram = true,
                            ShowMap = true,
                            ShowPhone = true,
                            ShowPhone2 = false,
                            ShowTikTok = false,
                            ShowWhatsApp = true,
                            ShowWorkingHours = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhatsApp = "+201000000000",
                            WorkingHoursAr = "السبت – الخميس: 10ص – 10م",
                            WorkingHoursEn = "Sat – Thu: 10AM – 10PM"
                        });
                });

            modelBuilder.Entity("FTD.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("FTD.Domain.Entities.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ContentBlocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyAr = "نقدم أفضل التكنولوجيا لحياة أفضل",
                            Key = "about.title.ar",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BodyEn = "Delivering The Best Technology For Better Life",
                            Key = "about.title.en",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BodyAr = "الفجر للتجارة شركة رائدة في بيع وتوزيع أجهزة التكنولوجيا الحديثة بأفضل الأسعار وأعلى جودة في السوق المصري.",
                            Key = "about.body.ar",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BodyEn = "Alfajr For Trade is a leading company in selling and distributing modern technology devices at the best prices and highest quality in the Egyptian market.",
                            Key = "about.body.en",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BodyAr = "10+",
                            BodyEn = "10+",
                            Key = "about.stat.years",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BodyAr = "50K+",
                            BodyEn = "50K+",
                            Key = "about.stat.clients",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BodyAr = "200+",
                            BodyEn = "200+",
                            Key = "about.stat.products",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BodyAr = "توفير أحدث التقنيات العالمية بأسعار عادلة وخدمة مبنية على الثقة والجودة والاحترافية في كل تفاصيل تجربة العميل.",
                            Key = "mission.text.ar",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BodyEn = "Providing the latest global technologies at fair prices with service built on trust, quality and professionalism in every detail of the customer experience.",
                            Key = "mission.text.en",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BodyAr = "أن نكون الوجهة الأولى والأكثر ثقة للتكنولوجيا في مصر والشرق الأوسط.",
                            Key = "vision.text.ar",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BodyEn = "To be the first and most trusted technology destination in Egypt and the Middle East.",
                            Key = "vision.text.en",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BodyAr = "وصل حديثاً",
                            Key = "hero.slide1.tag.ar",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BodyEn = "New Arrival",
                            Key = "hero.slide1.tag.en",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BodyAr = "لماذا Uni-Shop؟",
                            Key = "features.title.ar",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            BodyEn = "Why Uni-Shop?",
                            Key = "features.title.en",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            BodyAr = "ضمان أصلي على جميع المنتجات",
                            BodyEn = "Original warranty on all products",
                            Key = "features.1",
                            TitleAr = "✓",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            BodyAr = "توصيل سريع لجميع المحافظات",
                            BodyEn = "Fast delivery to all governorates",
                            Key = "features.2",
                            TitleAr = "🚚",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            BodyAr = "دعم فني على مدار الساعة",
                            BodyEn = "24/7 technical support",
                            Key = "features.3",
                            TitleAr = "💬",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            BodyAr = "سياسة إرجاع 14 يوم",
                            BodyEn = "14-day return policy",
                            Key = "features.4",
                            TitleAr = "↩",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            BodyAr = "تقسيط بدون فوائد",
                            BodyEn = "0% interest installments",
                            Key = "features.5",
                            TitleAr = "💳",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            BodyAr = "منتجات أصلية 100% معتمدة",
                            BodyEn = "100% authentic certified products",
                            Key = "features.6",
                            TitleAr = "⭐",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            BodyAr = "مباشر · الأكثر مبيعاً",
                            BodyEn = "LIVE · Best Seller Q3",
                            Key = "hero.chip1",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            BodyAr = "وصل حديثاً · ٢٤",
                            BodyEn = "New Arrivals · 24",
                            Key = "hero.chip2",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            BodyAr = "منصة التحكم",
                            BodyEn = "The command deck",
                            Key = "hero.title.line1",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            BodyAr = "للتكنولوجيا العصرية.",
                            BodyEn = "for modern tech.",
                            Key = "hero.title.line2",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            BodyAr = "لوحة تحكم ومنصة منسقة لأجهزة DOOGEE و JisuLife و Dreame — صُممت للمحترفين وتمت معايرتها للحياة اليومية. توصيل لكافة محافظات مصر بضمان معتمد.",
                            BodyEn = "A curated instrument panel of DOOGEE, JisuLife and Dreame hardware — engineered for professionals, calibrated for daily life. Delivered across Egypt with certified warranty.",
                            Key = "hero.subtitle",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            BodyAr = "اكتشف الكتالوج",
                            BodyEn = "Explore Catalog",
                            Key = "hero.btn1.text",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            BodyAr = "/Products",
                            Key = "hero.btn1.url",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            BodyAr = "المميز هذا الأسبوع",
                            BodyEn = "Featured this week",
                            Key = "hero.btn2.text",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            BodyAr = "#featured",
                            Key = "hero.btn2.url",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            BodyAr = "سنوات خبرة",
                            BodyEn = "Years Experience",
                            Key = "hero.stat1.label",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            BodyAr = "عميل سعيد",
                            BodyEn = "Delivered Orders",
                            Key = "hero.stat2.label",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            BodyAr = "منتج فريد",
                            BodyEn = "Curated SKUs",
                            Key = "hero.stat3.label",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            BodyAr = "ضمان معتمد",
                            BodyEn = "Certified Warranty",
                            Key = "value.prop1.title",
                            TitleAr = "bi-shield-check",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            BodyAr = "على جميع المنتجات",
                            BodyEn = "On every product",
                            Key = "value.prop1.desc",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            BodyAr = "توصيل سريع",
                            BodyEn = "Fast Delivery",
                            Key = "value.prop2.title",
                            TitleAr = "bi-truck",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            BodyAr = "لكل محافظات مصر",
                            BodyEn = "To all governorates",
                            Key = "value.prop2.desc",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            BodyAr = "دعم فني 24/7",
                            BodyEn = "24/7 Support",
                            Key = "value.prop3.title",
                            TitleAr = "bi-headset",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            BodyAr = "فريق متخصص دائماً",
                            BodyEn = "Expert team, always on",
                            Key = "value.prop3.desc",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            BodyAr = "استرجاع 14 يوم",
                            BodyEn = "14-Day Returns",
                            Key = "value.prop4.title",
                            TitleAr = "bi-arrow-counterclockwise",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            BodyAr = "بدون أي تعقيدات",
                            BodyEn = "Hassle-free policy",
                            Key = "value.prop4.desc",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            BodyAr = "تسوق حسب الفئة · ٠١",
                            BodyEn = "Shop by Category · 01",
                            Key = "cat.showcase.eyebrow",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            BodyAr = "اختر فئتك، واكتشف الأفضل.",
                            BodyEn = "Pick a category, discover the best.",
                            Key = "cat.showcase.title",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            BodyAr = "كل فئة منسقة بعناية — أجهزة مختارة من أفضل العلامات العالمية بمواصفات مؤكدة وأسعار تنافسية.",
                            BodyEn = "Every category is hand-curated — devices from top global brands with verified specs and competitive prices.",
                            Key = "cat.showcase.desc",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            BodyAr = "كتالوج المنتجات · ٠٢",
                            BodyEn = "Product Catalog · 02",
                            Key = "feat.catalog.eyebrow",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            BodyAr = "أجهزة منسقة لكل أسلوب عمل.",
                            BodyEn = "Curated hardware for every workflow.",
                            Key = "feat.catalog.title",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            BodyAr = "قم بالتصفية حسب الفئة لاستكشاف المنتجات الهامة فقط. تأتي جميع الوحدات مع ضمان معتمد ودعم فني متاح دائماً.",
                            BodyEn = "Filter by category to explore only what matters. Every unit ships with certified warranty and 24/7 technical support.",
                            Key = "feat.catalog.desc",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            BodyAr = "عرض جميع المنتجات",
                            BodyEn = "View All Products",
                            Key = "feat.catalog.btn.text",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            BodyAr = "جاهز ترتقي بأجهزتك؟ ابدأ التسوق الآن.",
                            BodyEn = "Ready to upgrade your gear? Start shopping now.",
                            Key = "cta.title",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            BodyAr = "منتجات أصلية 100% بضمان معتمد، توصيل سريع لباب البيت، وتقسيط بدون فوائد. تجربة تسوق عالمية بمعايير مصرية.",
                            BodyEn = "100% authentic products with certified warranty, fast door-to-door delivery, and 0% interest installments.",
                            Key = "cta.desc",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            BodyAr = "تسوق الآن",
                            BodyEn = "Shop Now",
                            Key = "cta.btn.text",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            BodyAr = "/Products",
                            Key = "cta.btn.url",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            BodyAr = "من نحن · ٠٣",
                            BodyEn = "About Us · 03",
                            Key = "about.eyebrow",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            BodyAr = "تقديم أفضل التكنولوجيا لحياة أكثر سهولة وذكاءً.",
                            BodyEn = "Delivering the best technology for a better life.",
                            Key = "about.headline",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            BodyAr = "رؤيتنا ورسالتنا · ٠٤",
                            BodyEn = "Mission & Vision · 04",
                            Key = "mission.eyebrow",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            BodyAr = "نبني مستقبل التكنولوجيا في مصر.",
                            BodyEn = "Building the tech future in Egypt.",
                            Key = "mission.headline",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            BodyAr = "تواصل معنا · ٠٥",
                            BodyEn = "Contact · 05",
                            Key = "contact.eyebrow",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            BodyAr = "نحن هنا لمساعدتك دائماً.",
                            BodyEn = "We're always here to help.",
                            Key = "contact.title",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            BodyAr = "تواصل مع فريق الدعم الفني والمبيعات مباشرة. نقوم بالرد على كافة الاستفسارات خلال ساعات العمل الرسمية.",
                            BodyEn = "Reach our support team directly. We respond to all requests within official working hours.",
                            Key = "contact.desc",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            BodyAr = "خلّيك أول من يعرف 🔥",
                            BodyEn = "Be the first to know 🔥",
                            Key = "newsletter.title",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            BodyAr = "اشترك ليصلك كل جديد عن المنتجات والعروض الحصرية قبل أي حد.",
                            BodyEn = "Subscribe for new arrivals and exclusive deals before anyone else.",
                            Key = "newsletter.desc",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            BodyAr = "اشترك",
                            BodyEn = "Subscribe",
                            Key = "newsletter.btn.text",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            BodyAr = "بوابتك المعتمدة لأحدث الأجهزة التكنولوجية من DOOGEE و JisuLife و Dreame. نوفر جودة فائقة وضمان حقيقي.",
                            BodyEn = "Your certified gateway for the latest tech hardware from DOOGEE, JisuLife, and Dreame. Delivering premium quality and certified warranty.",
                            Key = "footer.desc",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            BodyAr = "يونى شوب. جميع الحقوق محفوظة.",
                            BodyEn = "Uni-Shop. All Rights Reserved.",
                            Key = "footer.credits",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FTD.Domain.Entities.ContentPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ContentPages");
                });

            modelBuilder.Entity("FTD.Domain.Entities.NavigationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("OpenInNewTab")
                        .HasColumnType("bit");

                    b.Property<string>("PageSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StaticRoute")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("NavigationItems");
                });

            modelBuilder.Entity("FTD.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#1A6BFF",
                            Icon = "🆕",
                            NameAr = "جديد",
                            NameEn = "New",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#0E4FCC",
                            Icon = "✅",
                            NameAr = "مؤكد",
                            NameEn = "Confirmed",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#FF9500",
                            Icon = "📦",
                            NameAr = "في انتظار الشحن",
                            NameEn = "Pending Shipment",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#FF6B35",
                            Icon = "🚚",
                            NameAr = "مع شركة الشحن",
                            NameEn = "With Courier",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "#00C48C",
                            Icon = "🎉",
                            NameAr = "تم التسليم",
                            NameEn = "Delivered",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            ColorHex = "#FF3B30",
                            Icon = "↩️",
                            NameAr = "مرتجع",
                            NameEn = "Returned",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            ColorHex = "#6c757d",
                            Icon = "❌",
                            NameAr = "ملغي",
                            NameEn = "Cancelled",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("FTD.Domain.Entities.PageSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("PageSections");
                });

            modelBuilder.Entity("FTD.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "NEW",
                            BrandName = "DOOGEE",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescAr = "تابلت متطور بشاشة 11 بوصة بدقة 2K وأداء استثنائي مناسب للعمل والترفيه في كل مكان.",
                            DescEn = "Advanced tablet with 11\" 2K display and exceptional performance for work and entertainment everywhere.",
                            Emoji = "📱",
                            IsActive = true,
                            IsFeatured = true,
                            NameAr = "تابلت T30 Ultra",
                            NameEn = "T30 Ultra Tablet",
                            Price = 8999m,
                            ShortDescAr = "شاشة 11 بوصة، بطارية 8300mAh، معالج Helio G99",
                            ShortDescEn = "11\" display, 8300mAh battery, Helio G99 processor",
                            Slug = "doogee-t30-ultra",
                            SortOrder = 1,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Badge = "RUGGED",
                            BrandName = "DOOGEE",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescAr = "تابلت متين مقاوم للماء والغبار والصدمات وفق معيار IP68. مثالي للاستخدام الصناعي والمغامرات.",
                            DescEn = "Rugged tablet resistant to water, dust and shocks per IP68 standard. Ideal for industrial use and outdoor adventures.",
                            Emoji = "💪",
                            IsActive = true,
                            IsFeatured = true,
                            NameAr = "تابلت R20 متين",
                            NameEn = "R20 Rugged Tablet",
                            Price = 12500m,
                            ShortDescAr = "مقاوم للماء IP68، شاشة 10.4 بوصة، بطارية 15600mAh",
                            ShortDescEn = "IP68 waterproof, 10.4\" screen, 15600mAh battery",
                            Slug = "doogee-r20-rugged",
                            SortOrder = 2,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Badge = "HOT",
                            BrandName = "JISULIFE",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescAr = "مروحة محمولة ذكية ببطارية قوية تدوم حتى 24 ساعة بالسرعة المنخفضة.",
                            DescEn = "Smart portable fan with powerful battery lasting up to 24 hours on low speed.",
                            Emoji = "🌀",
                            IsActive = true,
                            IsFeatured = true,
                            NameAr = "مروحة محمولة F40",
                            NameEn = "F40 Portable Fan",
                            Price = 1299m,
                            ShortDescAr = "بطارية 10000mAh، تدوم حتى 24 ساعة، 4 سرعات",
                            ShortDescEn = "10000mAh battery, up to 24hrs, 4 speeds",
                            Slug = "jisulife-f40",
                            SortOrder = 1,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Badge = "",
                            BrandName = "JISULIFE",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescAr = "مروحة تُلبس حول الرقبة لراحة مستمرة. خفيفة جداً بوزن 135 جرام فقط.",
                            DescEn = "Wearable neck fan for continuous comfort without holding it. Ultra-light at only 135g.",
                            Emoji = "🌬️",
                            IsActive = true,
                            IsFeatured = false,
                            NameAr = "مروحة رقبة F8 Pro",
                            NameEn = "F8 Pro Neck Fan",
                            Price = 899m,
                            ShortDescAr = "تُلبس حول الرقبة، خفيفة 135 جرام، USB-C",
                            ShortDescEn = "Wearable neck design, 135g ultra-light, USB-C",
                            Slug = "jisulife-f8-pro",
                            SortOrder = 2,
                            Stock = 80
                        },
                        new
                        {
                            Id = 5,
                            Badge = "4K",
                            BrandName = "DREAME",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescAr = "كاميرا ويب احترافية بدقة 4K وعدسة واسعة مع ميكروفون مزدوج بإلغاء الضوضاء.",
                            DescEn = "Professional webcam with 4K resolution and 90° wide lens with dual noise-canceling microphone.",
                            Emoji = "📷",
                            IsActive = true,
                            IsFeatured = true,
                            NameAr = "كاميرا ويب 4K Pro",
                            NameEn = "4K Pro Webcam",
                            Price = 2499m,
                            ShortDescAr = "دقة 4K، عدسة واسعة 90 درجة، ميكروفون مدمج",
                            ShortDescEn = "4K resolution, 90° wide lens, built-in microphone",
                            Slug = "dreame-4k-pro",
                            SortOrder = 1,
                            Stock = 60
                        },
                        new
                        {
                            Id = 6,
                            Badge = "",
                            BrandName = "DREAME",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescAr = "كاميرا ويب 1080p بتصحيح تلقائي للإضاءة. Plug & Play بدون تثبيت برامج.",
                            DescEn = "1080p Full HD webcam with automatic light correction. Plug & Play with no software needed.",
                            Emoji = "🎥",
                            IsActive = true,
                            IsFeatured = false,
                            NameAr = "كاميرا ويب HD Stream",
                            NameEn = "HD Stream Webcam",
                            Price = 1199m,
                            ShortDescAr = "1080p Full HD، تصحيح تلقائي للإضاءة، Plug & Play",
                            ShortDescEn = "1080p Full HD, auto light correction, Plug & Play",
                            Slug = "dreame-hd-stream",
                            SortOrder = 2,
                            Stock = 70
                        });
                });

            modelBuilder.Entity("FTD.Domain.Entities.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductAttributes");
                });

            modelBuilder.Entity("FTD.Domain.Entities.ProductAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeValueId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("AttributeValueId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttributeValues");
                });

            modelBuilder.Entity("FTD.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("FTD.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("FTD.Domain.Entities.SalesOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("SalesOrderDetails");
                });

            modelBuilder.Entity("FTD.Domain.Entities.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "اسم الموقع",
                            Key = "site.name",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "Uni-Shop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "الشعار بالعربي",
                            Key = "site.tagline.ar",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "يونى شوب للمبيعات"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tagline English",
                            Key = "site.tagline.en",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "Uni-Shop E-Commerce"
                        },
                        new
                        {
                            Id = 4,
                            Description = "اللون الأساسي",
                            Key = "site.primary.color",
                            Type = "color",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "#1A6BFF"
                        },
                        new
                        {
                            Id = 5,
                            Description = "شحن مجاني فوق (EGP)",
                            Key = "shipping.free.above",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "5000"
                        },
                        new
                        {
                            Id = 6,
                            Description = "رسوم الشحن (EGP)",
                            Key = "shipping.fee",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "150"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Meta Title",
                            Key = "meta.title.ar",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "Uni-Shop — وجهتك للتسوق"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Meta Desc AR",
                            Key = "meta.desc.ar",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "وجهتك الأولى لأحدث التكنولوجيا في مصر"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Meta Desc EN",
                            Key = "meta.desc.en",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "Your first destination for the latest technology in Egypt"
                        },
                        new
                        {
                            Id = 10,
                            Description = "منتجات سلايدر الهيرو (IDs مرتبة)",
                            Key = "homepage.hero.products",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1,3,5"
                        },
                        new
                        {
                            Id = 11,
                            Description = "منتجات الكتالوج المميز (IDs مرتبة)",
                            Key = "homepage.featured.products",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1,2,3,4,5,6"
                        },
                        new
                        {
                            Id = 12,
                            Description = "إظهار قسم الهيرو",
                            Key = "homepage.show.hero",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1"
                        },
                        new
                        {
                            Id = 13,
                            Description = "إظهار شريط المزايا",
                            Key = "homepage.show.values",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1"
                        },
                        new
                        {
                            Id = 15,
                            Description = "إظهار معرض الفئات",
                            Key = "homepage.show.categories",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1"
                        },
                        new
                        {
                            Id = 16,
                            Description = "إظهار الكتالوج المميز",
                            Key = "homepage.show.featured",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1"
                        },
                        new
                        {
                            Id = 17,
                            Description = "إظهار قسم من نحن",
                            Key = "homepage.show.about",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1"
                        },
                        new
                        {
                            Id = 18,
                            Description = "إظهار الرؤية والرسالة",
                            Key = "homepage.show.mission",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1"
                        },
                        new
                        {
                            Id = 19,
                            Description = "إظهار شريط CTA",
                            Key = "homepage.show.cta",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1"
                        },
                        new
                        {
                            Id = 20,
                            Description = "إظهار قسم التواصل",
                            Key = "homepage.show.contact",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1"
                        },
                        new
                        {
                            Id = 21,
                            Description = "إظهار النشرة البريدية بالفوتر",
                            Key = "homepage.show.newsletter",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1"
                        },
                        new
                        {
                            Id = 22,
                            Description = "إظهار شارات الدفع بالفوتر",
                            Key = "homepage.show.payments",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "1"
                        },
                        new
                        {
                            Id = 23,
                            Description = "ترتيب أقسام الرئيسية",
                            Key = "homepage.sections.order",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "hero,values,categories,featured,about,mission,cta,contact"
                        },
                        new
                        {
                            Id = 24,
                            Description = "عدد بلاطات الفئات بالرئيسية",
                            Key = "homepage.categories.count",
                            Type = "text",
                            UpdatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FTD.Domain.Entities.AttributeValue", b =>
                {
                    b.HasOne("FTD.Domain.Entities.ProductAttribute", "Attribute")
                        .WithMany("Values")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("FTD.Domain.Entities.NavigationItem", b =>
                {
                    b.HasOne("FTD.Domain.Entities.NavigationItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FTD.Domain.Entities.PageSection", b =>
                {
                    b.HasOne("FTD.Domain.Entities.ContentPage", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("FTD.Domain.Entities.Product", b =>
                {
                    b.HasOne("FTD.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FTD.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FTD.Domain.Entities.ProductAttribute", b =>
                {
                    b.HasOne("FTD.Domain.Entities.Category", "Category")
                        .WithMany("Attributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FTD.Domain.Entities.ProductAttributeValue", b =>
                {
                    b.HasOne("FTD.Domain.Entities.ProductAttribute", "Attribute")
                        .WithMany("ProductValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FTD.Domain.Entities.AttributeValue", "AttributeValue")
                        .WithMany("ProductValues")
                        .HasForeignKey("AttributeValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FTD.Domain.Entities.Product", "Product")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("AttributeValue");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FTD.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("FTD.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FTD.Domain.Entities.SalesOrder", b =>
                {
                    b.HasOne("FTD.Domain.Entities.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FTD.Domain.Entities.SalesOrderDetail", b =>
                {
                    b.HasOne("FTD.Domain.Entities.SalesOrder", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FTD.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FTD.Domain.Entities.AttributeValue", b =>
                {
                    b.Navigation("ProductValues");
                });

            modelBuilder.Entity("FTD.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FTD.Domain.Entities.Category", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("FTD.Domain.Entities.ContentPage", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("FTD.Domain.Entities.NavigationItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("FTD.Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FTD.Domain.Entities.Product", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("Images");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("FTD.Domain.Entities.ProductAttribute", b =>
                {
                    b.Navigation("ProductValues");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("FTD.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
