import 'package:flutter/material.dart';

import '../theme/app_colors.dart';
import '../theme/app_spacing.dart';

/// The Uni-Shop brand mark: the "US" shopping-cart monogram.
///
/// This renders `assets/branding/logo-mark*.png`, generated by
/// `tool/generate_launcher_icons.py` from the website's own
/// `wwwroot/images/logo-unishop-icon.png`. Sharing one source with the site
/// and the launcher icon is what keeps all three identical.
///
/// An earlier version drew the mark with a CustomPainter ported from
/// `logo-unishop.svg`. That was abandoned: the committed SVG is a rough
/// approximation of the brand (a thin open stroke), so the painted result did
/// not look like the logo a visitor sees. Shipping the real artwork is more
/// faithful than re-deriving it.
class AppLogo extends StatelessWidget {
  const AppLogo({
    super.key,
    this.height = 30,
    this.light = false,
    this.showWordmark = true,
  });

  /// Logical height of the mark. Width follows the artwork's aspect ratio.
  final double height;

  /// Use the white version, for placement on a purple or dark surface.
  final bool light;

  /// Whether to draw the "Uni-Shop" wordmark beside the mark.
  final bool showWordmark;

  @override
  Widget build(BuildContext context) {
    final mark = Image.asset(
      light
          ? 'assets/branding/logo-mark-light.png'
          : 'assets/branding/logo-mark.png',
      height: height,
      // The asset is authored at 180px tall for a ~40px slot, so it is always
      // downscaled; without a cache hint Flutter would decode it at full size
      // and hold the larger bitmap in memory for every logo on screen.
      cacheHeight: (height * MediaQuery.devicePixelRatioOf(context)).round(),
      filterQuality: FilterQuality.medium,
      // Decorative on its own — the Semantics wrapper below names the whole
      // lockup once, so the image must not announce itself a second time.
      excludeFromSemantics: true,
    );

    if (!showWordmark) {
      return Semantics(label: 'Uni-Shop', image: true, child: mark);
    }

    return Semantics(
      label: 'Uni-Shop',
      image: true,
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          mark,
          const SizedBox(width: AppSpacing.xs),
          Text(
            'Uni-Shop',
            // Latin brand name: forced LTR so it renders correctly inside the
            // app's RTL directionality.
            textDirection: TextDirection.ltr,
            style: TextStyle(
              fontSize: height * 0.62,
              fontWeight: FontWeight.w800,
              // The site's wordmark is italic with tight tracking
              // (`font-style: italic; letter-spacing: -0.03em`).
              fontStyle: FontStyle.italic,
              letterSpacing: height * 0.62 * -0.03,
              height: 1,
              color: light ? Colors.white : AppColors.primary,
            ),
          ),
        ],
      ),
    );
  }
}
